# Generated by Django 2.0.3 on 2018-06-08 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0003_auto_20180505_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('roam', 'Roam'), ('stratop', 'Strategic Operation'), ('cta', 'Call to Arms')], max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('aar', models.URLField(blank=True, max_length=255, null=True)),
                ('fc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCharacter')),
            ],
            options={
                'permissions': (('create_fleet', 'Can create a fleet.'),),
            },
        ),
        migrations.CreateModel(
            name='FleetPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('fleet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.Fleet')),
            ],
        ),
    ]
