# Generated by Django 2.0.3 on 2018-06-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleet',
            options={'permissions': (('view_fleet', 'Can view a fleet.'), ('view_all_fleets', 'Can create a fleet.'))},
        ),
    ]
