# Generated by Django 2.0.3 on 2018-06-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0003_auto_20180505_0910'),
        ('fleet', '0002_auto_20180608_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetpoint',
            name='character_id',
        ),
        migrations.AddField(
            model_name='fleetpoint',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCharacter'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='type',
            field=models.CharField(blank=True, choices=[('mining', 'Mining Fleet'), ('roam', 'Roam'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
