# Generated by Django 2.0.3 on 2018-06-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20180608_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetpoint',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
