# Generated by Django 2.0.3 on 2018-06-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_fleetpoint_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
