# Generated by Django 2.0.3 on 2018-06-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_auto_20180608_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
