# Generated by Django 2.0.3 on 2018-07-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_auto_20180608_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='fleetpoint',
            name='character',
        ),
        migrations.RemoveField(
            model_name='fleetpoint',
            name='fleet',
        ),
        migrations.DeleteModel(
            name='Fleet',
        ),
        migrations.DeleteModel(
            name='FleetPoint',
        ),
    ]
