# Generated by Django 2.0.3 on 2018-07-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0003_auto_20180505_0910'),
        ('core', '0004_auto_20180703_2116'),
        ('fleet', '0008_auto_20180703_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Event')),
                ('eve_id', models.BigIntegerField()),
                ('type', models.CharField(blank=True, choices=[('cta', 'Call to Arms'), ('mining', 'Mining'), ('roam', 'Roam'), ('other', 'Other')], max_length=255, null=True)),
                ('aar', models.URLField(blank=True, max_length=255, null=True)),
                ('fc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCharacter')),
            ],
            options={
                'permissions': (('view_fleet', 'Can view a fleet.'), ('view_all_fleets', 'Can create a fleet.')),
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='FleetPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCharacter')),
                ('fleet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.Fleet')),
            ],
        ),
    ]
