# Generated by Django 2.0.3 on 2018-05-25 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0002_discourseuser_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discourseuser',
            name='auth_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
