# Generated by Django 2.0.2 on 2018-02-24 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discourse', '0002_discourseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discourseuser',
            name='group',
        ),
        migrations.AddField(
            model_name='discourseuser',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
