# Generated by Django 2.0.2 on 2018-02-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0003_auto_20180224_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='discourseuser',
            name='groups',
            field=models.ManyToManyField(to='discourse.DiscourseGroup'),
        ),
    ]
