# Generated by Django 2.0.3 on 2018-07-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0004_discourseuser_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discourseuser',
            name='external_id',
        ),
    ]
