# Generated by Django 2.0.3 on 2018-04-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0004_discourseuser_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discoursegroup',
            old_name='role_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='discourseuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
