# Generated by Django 2.0.3 on 2018-04-21 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscordToken',
            new_name='DiscordUser',
        ),
    ]
