# Generated by Django 2.0.3 on 2018-05-22 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_auto_20180507_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
