# Generated by Django 2.0.1 on 2018-01-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_discordrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordrole',
            name='id',
        ),
        migrations.AlterField(
            model_name='discordrole',
            name='role_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
