# Generated by Django 2.0.3 on 2018-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_auto_20180421_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='userid',
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
