# Generated by Django 2.0.3 on 2018-04-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0004_auto_20180421_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='groups',
            field=models.ManyToManyField(to='discord.DiscordGroup'),
        ),
    ]
