# Generated by Django 2.1.5 on 2019-01-25 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=3)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'permissions': (('manage_events', 'Can manage events'),),
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_finished', models.DateField()),
                ('url', models.CharField(max_length=256)),
                ('survey_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
