# Generated by Django 2.1.5 on 2019-01-26 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=3)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guilds.Guild')),
                ('participants', models.ManyToManyField(blank=True, related_name='events_participated', to=settings.AUTH_USER_MODEL)),
                ('registrants', models.ManyToManyField(blank=True, related_name='events_registered', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('manage_events', 'Can manage events'),),
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_finished', models.DateField()),
                ('url', models.CharField(max_length=256)),
                ('survey_key', models.UUIDField(default=uuid.uuid4)),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guilds.Guild')),
                ('users_completed', models.ManyToManyField(blank=True, related_name='surveys_completed', to=settings.AUTH_USER_MODEL)),
                ('users_started', models.ManyToManyField(blank=True, related_name='surveys_started', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
