# Generated by Django 2.1.5 on 2019-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='group',
        ),
        migrations.AddField(
            model_name='guild',
            name='groups',
            field=models.ManyToManyField(related_name='guilds', to='auth.Group'),
        ),
    ]
