version: '2.0'

services:
    db:
        image: mysql:5.7
        volumes:
            - database:/var/lib/mysql
        restart: always
        command: --max_allowed_packet=256M
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

    redis:
        image: redis:6.0.9-alpine
        volumes:
            - "redis:/var/lib/redis"
            - "redis:/data"

    app:
        image: kryptedgaming/krypted:latest
        env_file: .env
        entrypoint: app_entrypoint.sh
        ports:
            - "8000:8000"
        depends_on:
            - db
    
    celery:
        image: kryptedgaming/krypted:latest
        restart: always
        env_file: .env
        entrypoint: celery_entrypoint.sh
        depends_on:
            - db
            - app 

volumes:
    database: {}
    redis: {}
