# Generated by Django 2.1.5 on 2019-01-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildapplicationtemplate',
            name='guild',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_template', to='guilds.Guild'),
        ),
    ]
