# Generated by Django 2.2.4 on 2019-11-15 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=16)),
                ('request_date', models.DateField(auto_now=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('response_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('RESPONSE', 'Response'), ('MODAL', 'Modal')], max_length=16)),
                ('choices', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('groups_to_add', models.ManyToManyField(blank=True, related_name='groups_to_add', to='auth.Group')),
                ('groups_to_remove', models.ManyToManyField(blank=True, related_name='groups_to_remove', to='auth.Group')),
                ('questions', models.ManyToManyField(blank=True, to='applications.ApplicationQuestion')),
                ('required_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('request_user', 'template')},
        ),
    ]
