# Generated by Django 2.2.8 on 2020-01-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('applications', '0002_auto_20191117_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationtemplate',
            options={'permissions': [('bypass_required_group_to_manage', 'Can approve, reject, and view applications despite their required manager groups')]},
        ),
        migrations.RenameField(
            model_name='applicationtemplate',
            old_name='required_group',
            new_name='required_group_to_apply',
        ),
        migrations.AddField(
            model_name='applicationtemplate',
            name='required_group_to_manage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_group', to='auth.Group'),
        ),
    ]
