# Generated by Django 2.0.2 on 2018-03-19 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveCorporation',
            fields=[
                ('corporation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('ticker', models.CharField(max_length=5)),
                ('member_count', models.IntegerField()),
                ('alliance_id', models.IntegerField()),
                ('tax_rate', models.FloatField()),
                ('ceo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCharacter')),
            ],
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='corporation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporation'),
            preserve_default=False,
        ),
    ]
