# Generated by Django 2.0.3 on 2018-11-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0002_auto_20181112_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='character_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
