# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0002_auto_20170824_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
