# Generated by Django 2.0.1 on 2018-01-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0002_evecharacter_character_alt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='character_alliance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='character_corporation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='character_alt_type',
            field=models.CharField(choices=[('pvp_alt', 'PvP Alt'), ('cap_alt', 'Capital Alt'), ('industry_alt', 'Industry Alt'), ('useless_alt', 'Useless Alt')], max_length=255, null=True),
        ),
    ]
