# Generated by Django 2.0.2 on 2018-03-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0003_auto_20180319_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecorporation',
            name='alliance_id',
            field=models.IntegerField(null=True),
        ),
    ]
