# Generated by Django 2.1.3 on 2018-11-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0003_evecharacter_character_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='character_id',
        ),
        migrations.RemoveField(
            model_name='token',
            name='character_name',
        ),
        migrations.RemoveField(
            model_name='token',
            name='character_owner_hash',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
    ]
