# Generated by Django 2.0.3 on 2018-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0004_auto_20180319_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecharacter',
            name='character_alt_type',
            field=models.CharField(blank=True, choices=[('pvp_alt', 'PvP Alt'), ('cap_alt', 'Capital Alt'), ('industry_alt', 'Industry Alt'), ('useless_alt', 'Useless Alt')], max_length=255, null=True),
        ),
    ]
