# Generated by Django 2.1.3 on 2018-11-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0004_auto_20181126_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
