# Generated by Django 2.0.3 on 2018-12-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0005_auto_20181130_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evecharacter',
            options={'permissions': (('audit_eve_character', 'Can audit an EVE character.'),)},
        ),
    ]
