# Generated by Django 2.0.3 on 2018-12-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0006_auto_20181209_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='scopes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
