# Generated by Django 2.1.4 on 2018-12-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0008_auto_20181216_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecharacter',
            name='character_alt_type',
            field=models.CharField(blank=True, choices=[('super_alt', 'Super Alt'), ('rorqual_alt', 'Rorqual Alt'), ('cap_alt', 'Capital Alt'), ('subcap_pve_alt', 'Subcap PvE Alt'), ('subcap_pvp_alt', 'Subcap PvP Alt'), ('industry_alt', 'Industry Alt'), ('useless_alt', 'Useless Alt')], max_length=255, null=True),
        ),
    ]
