# Generated by Django 2.1.5 on 2019-01-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecorporation',
            name='blue_entity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evecorporation',
            name='primary_entity',
            field=models.BooleanField(default=False),
        ),
    ]
