# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170609_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pinned_games',
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
