# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_game_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='game',
        ),
    ]
