# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_notification_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='source',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
