# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='importance',
            field=models.CharField(blank=True, choices=[(b'1', b'Low'), (b'2', b'Medium'), (b'3', b'High')], max_length=12, null=True),
        ),
    ]
