# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_event_importance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, unique=True)),
                ('image', models.URLField(blank=True, max_length=256, null=True)),
                ('slug', models.CharField(blank=True, max_length=24, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('leadership', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
        migrations.RemoveField(
            model_name='game',
            name='leadership',
        ),
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='game',
            name='source',
        ),
    ]
