# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170712_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='guilds',
            field=models.ManyToManyField(to='core.Guild'),
        ),
    ]
