# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_profile_guilds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='id',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='leadership',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guilds',
        ),
        migrations.AddField(
            model_name='game',
            name='leadership',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guild',
            name='game_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Game'),
            preserve_default=False,
        ),
    ]
