# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170712_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='guilds',
            field=models.ManyToManyField(related_name='guilds', to='core.Guild'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(related_name='games', to='core.Game'),
        ),
    ]
