# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170712_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
