# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, choices=[(b'EU', b'EU'), (b'US', b'US')], max_length=2, null=True),
        ),
    ]
