# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170718_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.CharField(blank=True, choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, choices=[('EU', 'EU'), ('US', 'US')], max_length=2, null=True),
        ),
    ]
