# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170718_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='text',
            new_name='message',
        ),
    ]
