# Generated by Django 2.1.4 on 2018-12-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20181229_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('event_log', 'Event Logs')], max_length=32)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
