# Generated by Django 2.1.4 on 2018-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_statisticlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticlog',
            name='type',
            field=models.CharField(choices=[('event_log', 'Event Logs')], max_length=32, unique=True),
        ),
    ]
