# Generated by Django 2.0.1 on 2018-02-09 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(auto_now=True)),
                ('date_occuring', models.DateTimeField()),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.CharField(blank=True, max_length=32, null=True)),
                ('importance', models.CharField(blank=True, choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=12, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('message', models.CharField(max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.CharField(blank=True, max_length=1500, null=True)),
                ('timezone', models.CharField(blank=True, choices=[('EU', 'EU'), ('US', 'US')], max_length=2, null=True)),
                ('points', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('twitter', models.URLField(blank=True, max_length=32, null=True)),
                ('steam', models.URLField(blank=True, max_length=255, null=True)),
                ('blizzard', models.CharField(blank=True, max_length=32, null=True)),
                ('discord', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Game')),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=24, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            bases=('core.game',),
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(related_name='games', to='core.Game'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='leadership',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='guilds',
            field=models.ManyToManyField(related_name='guilds', to='core.Guild'),
        ),
    ]
