# Generated by Django 2.0.2 on 2018-03-18 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEntity',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.Group')),
                ('description', models.CharField(blank=True, max_length=512)),
                ('hidden', models.BooleanField(default=True, help_text='Hidden from the apply menu.')),
                ('public', models.BooleanField(default=False, help_text='Automatically join upon request.')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Vetoed', 'Vetoed')], max_length=32)),
                ('date_requested', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GroupEntity')),
            ],
        ),
        migrations.AddField(
            model_name='groupentity',
            name='managers',
            field=models.ManyToManyField(help_text='Users who can accept/decline requests.', to=settings.AUTH_USER_MODEL),
        ),
    ]
