# Generated by Django 2.0.1 on 2018-01-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.CharField(blank=True, choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, choices=[('EU', 'EU'), ('US', 'US')], max_length=2, null=True),
        ),
    ]
