# Generated by Django 2.1.3 on 2018-11-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildapplicationquestion',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
