# Generated by Django 2.0.3 on 2018-07-02 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180702_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupentity',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Users who can accept/decline requests.', to=settings.AUTH_USER_MODEL),
        ),
    ]
