# Generated by Django 2.1.3 on 2018-11-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181111_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildapplicationquestion',
            name='choices',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='guildapplicationquestion',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
