# Generated by Django 2.1.5 on 2019-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_groupinfo_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('fa_icon', models.CharField(max_length=32)),
                ('link', models.URLField()),
            ],
        ),
    ]
