# Generated by Django 2.1.3 on 2018-11-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181111_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('manage_group_requests', 'Can manage group requests.'), ('audit_group_requests', 'Can audit group requests.'))},
        ),
    ]
