# Generated by Django 2.0.3 on 2018-07-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180703_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupentity',
            name='guild',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Guild'),
        ),
    ]
