# Generated by Django 2.1.3 on 2018-11-11 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181111_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_guild', to='core.Guild'),
        ),
    ]
