# Generated by Django 2.0.3 on 2018-07-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_groupentity_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupentity',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Guild'),
        ),
    ]
