# Generated by Django 2.1.3 on 2018-11-11 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181111_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprequest',
            name='request_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
    ]
