# Generated by Django 2.1.4 on 2018-12-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181220_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
