# Generated by Django 2.1.4 on 2018-12-21 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181220_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='registrants',
            field=models.ManyToManyField(blank=True, related_name='registrants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='password',
            field=models.CharField(default=780, max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
