# Generated by Django 2.1.4 on 2018-12-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181221_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('manage_events', 'Can manage events'),)},
        ),
        migrations.AlterField(
            model_name='event',
            name='password',
            field=models.CharField(max_length=3),
        ),
    ]
