# Generated by Django 2.1.4 on 2018-12-28 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181224_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
