# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapplications', '0003_applicationtemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=1200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='application',
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrapplications.Question'),
        ),
    ]
