# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrapplications', '0004_auto_20170820_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='response_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
