# Generated by Django 2.0.1 on 2018-01-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='Processing', max_length=24),
        ),
    ]
