# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('hrapplications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild', to='core.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='application',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrapplications.Application'),
        ),
        migrations.AddField(
            model_name='comment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrapplications.Application'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationtemplate',
            name='questions',
            field=models.ManyToManyField(related_name='application_questions', to='hrapplications.Question'),
        ),
        migrations.AddField(
            model_name='application',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrapplications.ApplicationTemplate'),
        ),
    ]
