# Generated by Django 2.0.3 on 2018-05-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('view_applications', 'Can view all applications'), ('view_application', 'Can view individual applications'), ('approve_application', 'Can approve an application'), ('deny_application', 'Can deny an application'))},
        ),
    ]
