# Generated by Django 2.0.1 on 2018-02-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapplications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_choices',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Blank', 'Blank'), ('Modal', 'Modal')], default='Blank', max_length=12),
        ),
    ]
