# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapplications', '0002_auto_20170817_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtemplate',
            name='name',
            field=models.CharField(default='APP', max_length=32),
            preserve_default=False,
        ),
    ]
