# Generated by Django 2.0.3 on 2018-05-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapplications', '0002_auto_20180209_0325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('view_applications', 'Can view all applications'), ('approve_application', 'Can approve an application'), ('deny_application', 'Can deny an application'))},
        ),
    ]
