# Generated by Django 2.0.3 on 2018-05-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapplications', '0003_auto_20180505_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
