# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapplications', '0005_response_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reponses',
            field=models.ManyToManyField(blank=True, null=True, related_name='application_responses', to='hrapplications.Response'),
        ),
    ]
