# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateCharacter',
            fields=[
                ('character_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MainCharacter',
            fields=[
                ('character_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField(blank=True, null=True)),
                ('character_owner_hash', models.CharField(max_length=256)),
                ('character_name', models.CharField(max_length=256)),
                ('access_token', models.CharField(max_length=128)),
                ('refresh_token', models.CharField(max_length=128)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='maincharacter',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eveonline.Token'),
        ),
        migrations.AddField(
            model_name='maincharacter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alternatecharacter',
            name='main',
            field=models.ManyToManyField(to='eveonline.MainCharacter'),
        ),
        migrations.AddField(
            model_name='alternatecharacter',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eveonline.Token'),
        ),
    ]
