# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0002_token_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternatecharacter',
            name='main',
        ),
        migrations.RemoveField(
            model_name='alternatecharacter',
            name='token',
        ),
        migrations.AddField(
            model_name='maincharacter',
            name='main',
            field=models.ManyToManyField(blank=True, null=True, to='eveonline.MainCharacter'),
        ),
        migrations.DeleteModel(
            name='AlternateCharacter',
        ),
    ]
