# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0003_auto_20170622_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainCharacter',
            new_name='EveCharacter',
        ),
    ]
