# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0005_auto_20170622_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_in',
            field=models.IntegerField(default=0),
        ),
    ]
