# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0006_auto_20170622_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='character_portrait',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
