# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0008_auto_20170712_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evecharacter',
            name='main',
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCharacter'),
        ),
    ]
