# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0009_auto_20170721_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expiry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
