# Generated by Django 2.0.3 on 2018-06-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='channels',
            field=models.ManyToManyField(to='slack.SlackChannel'),
        ),
        migrations.AlterField(
            model_name='slackchannel',
            name='slack_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='slack_id',
            field=models.IntegerField(),
        ),
    ]
