# Generated by Django 2.0.3 on 2018-06-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_auto_20180601_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackchannel',
            name='slack_id',
        ),
    ]
