# Generated by Django 2.0.3 on 2018-03-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0003_auto_20180328_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackchannel',
            name='name',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
    ]
