# Generated by Django 2.0.3 on 2018-06-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_slackchannel_slack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='slack_id',
            field=models.CharField(max_length=32),
        ),
    ]
